# Generated by Django 5.1.1 on 2024-10-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colorvariant_sizevariant_product_color_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(to='product.sizevariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_variant',
            field=models.ManyToManyField(to='product.colorvariant'),
        ),
    ]
