# Generated by Django 5.1.1 on 2024-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(default='10-10-2024'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=20),
        ),
    ]
