# Generated by Django 5.1.1 on 2024-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_coupon_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default='2024-10-10'),
        ),
    ]
