# Generated by Django 5.1.1 on 2024-10-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_coupon_expiry_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
